@startuml

title "Node-Red UML Class Diagramm"

Webservices *-- Service
file_system <-- Webservices
set namespaceSeparator none
mqtt_ip_address.config <-- Webservices
interface file_system
Webservices o-- Alarm
Service o-- Alarm
Webservices *-- MqttInterface
mqtt <-- MqttInterface
interface mqtt

Webservices : MqttInterface : MqttInterface
Webservices : startTime : int
Webservices : mqtt_ip_address :  string
Webservices : allGeneratedAlarms : [Alarm]
Webservices : generatedServices : [Service]
Webservices : generateAlarm(service : Service)
Webservices : generateSimData()
Webservices : validateIPaddress(ipaddress : string) : boolean
Webservices : brokerUrl : string
Webservices : clientId : string
Webservices : client : MqttClient


Service : sensorType : string
Service : valueType : string
Service : value : int
Service : unit : int
Service : valueCounterDirection : string
Service : port : int
Service : addAlarm(alarm : Alarm)
Service : setValueCounterDirection(direction : string)
Service : setValue(value : int)

Alarm : type : string
Alarm : timestamp : int
Alarm : argument :string

MqttInterface : sendAlarm(client: MqttClient, alarm : Alarm)
MqttInterface : sendData(client: MqttClient, service : Service)
MqttInterface : sendClientHello(client: MqttClient)

class mqtt_ip_address.config << (F,#FF7700) File >>
mqtt_ip_address.config : IP-ADDRESS

@enduml