@startuml

title "Node-Red UML Class Diagramm"

Webservices *-- Service
file_system <-- Webservices
interface file_system
Webservices o-- Alarm
Service o-- Alarm
Webservices *-- MqttInterface
mqtt <-- MqttInterface
interface mqtt

Webservices : mqttClient : MqttInterface
Webservices : startTime : int
Webservices : mqtt_ip_address :  string
Webservices : allGeneratedAlarms : [Alarm]
Webservices : generatedServices : [Service]
Webservices : generateAlarm(service : Service)
Webservices : generateSimData()
Webservices : validateIPaddress(ipaddress : string) : boolean

Service : sensorType : string
Service : valueType : string
Service : value : int
Service : unit : int
Service : valueCounterDirection : string
Service : port : int
Service : addAlarm(alarm : Alarm)
Service : setValueCounterDirection(direction : string)
Service : setValue(value : int)

Alarm : type : string
Alarm : timestamp : int
Alarm : argument :string

MqttInterface : brokerUrl : string
MqttInterface : client : MqttClient
MqttInterface : sendAlarm(alarm : Alarm)
MqttInterface : sendData(service : Service)
MqttInterface : sendClientHello()

@enduml